lib: [
  "/home/mrkaspa/code/ml/esy-ocaml/node_modules/.cache/_esy/store/b/csv-0.1.0-b10fd6b6/install/default/lib/csv_lib/META" {"META"}
  "/home/mrkaspa/code/ml/esy-ocaml/node_modules/.cache/_esy/store/b/csv-0.1.0-b10fd6b6/install/default/lib/csv_lib/opam" {"opam"}
  "/home/mrkaspa/code/ml/esy-ocaml/node_modules/.cache/_esy/store/b/csv-0.1.0-b10fd6b6/install/default/lib/csv_lib/lib.cmi" {"lib.cmi"}
  "/home/mrkaspa/code/ml/esy-ocaml/node_modules/.cache/_esy/store/b/csv-0.1.0-b10fd6b6/install/default/lib/csv_lib/lib.cmx" {"lib.cmx"}
  "/home/mrkaspa/code/ml/esy-ocaml/node_modules/.cache/_esy/store/b/csv-0.1.0-b10fd6b6/install/default/lib/csv_lib/lib.cmt" {"lib.cmt"}
  "/home/mrkaspa/code/ml/esy-ocaml/node_modules/.cache/_esy/store/b/csv-0.1.0-b10fd6b6/install/default/lib/csv_lib/lib.ml-gen" {"lib.ml-gen"}
  "/home/mrkaspa/code/ml/esy-ocaml/node_modules/.cache/_esy/store/b/csv-0.1.0-b10fd6b6/install/default/lib/csv_lib/lib__Util.cmi" {"lib__Util.cmi"}
  "/home/mrkaspa/code/ml/esy-ocaml/node_modules/.cache/_esy/store/b/csv-0.1.0-b10fd6b6/install/default/lib/csv_lib/lib__Util.cmx" {"lib__Util.cmx"}
  "/home/mrkaspa/code/ml/esy-ocaml/node_modules/.cache/_esy/store/b/csv-0.1.0-b10fd6b6/install/default/lib/csv_lib/lib__Util.cmt" {"lib__Util.cmt"}
  "/home/mrkaspa/code/ml/esy-ocaml/node_modules/.cache/_esy/store/b/csv-0.1.0-b10fd6b6/install/default/lib/csv_lib/Util.ml" {"Util.ml"}
  "/home/mrkaspa/code/ml/esy-ocaml/node_modules/.cache/_esy/store/b/csv-0.1.0-b10fd6b6/install/default/lib/csv_lib/lib.cma" {"lib.cma"}
  "/home/mrkaspa/code/ml/esy-ocaml/node_modules/.cache/_esy/store/b/csv-0.1.0-b10fd6b6/install/default/lib/csv_lib/lib.cmxa" {"lib.cmxa"}
  "/home/mrkaspa/code/ml/esy-ocaml/node_modules/.cache/_esy/store/b/csv-0.1.0-b10fd6b6/install/default/lib/csv_lib/lib.a" {"lib.a"}
  "/home/mrkaspa/code/ml/esy-ocaml/node_modules/.cache/_esy/store/b/csv-0.1.0-b10fd6b6/install/default/lib/csv_lib/lib.cmxs" {"lib.cmxs"}
  "/home/mrkaspa/code/ml/esy-ocaml/node_modules/.cache/_esy/store/b/csv-0.1.0-b10fd6b6/install/default/lib/csv_lib/csv_lib.dune" {"csv_lib.dune"}
]
bin: [
  "/home/mrkaspa/code/ml/esy-ocaml/node_modules/.cache/_esy/store/b/csv-0.1.0-b10fd6b6/install/default/bin/Csv_bin" {"Csv_bin"}
]
doc: [
  "/home/mrkaspa/code/ml/esy-ocaml/node_modules/.cache/_esy/store/b/csv-0.1.0-b10fd6b6/install/default/doc/csv_lib/README.md"
]
